site_name: IX-train
repo_name: GitHub
repo_url: https://github.com/jonathon-langford/ix-train
edit_uri: edit/main/docs

nav:
        - Home: index.md

theme:
        name: readthedocs
        logo: imperial_x_logo.jpeg
        favicon: imperial_x_logo.jpeg
        custom_dir: docs/overrides
        features:
            - content.code.copy
            - navigation.footer
            - navigation.indexes
            - navigation.expand
            - navigation.tracking
            - navigation.tabs
            - navigation.tabs.sticky
            - navigation.top
            - search.highlight
            - search.suggest
            - toc.follow

plugins:
    - search

extra:
    version:
        provider: mike

extra_css:
  - "mystyle.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
